title: "Reuben Larsen's Portfolio"
description: "Aerospace Engineer — sharing projects over the years."
author: "Reuben Larsen"
email: "you@email.com"
github_username: yourusername

baseurl: "/Portfolio"
url: "https://Reub2003.github.io/Portfolio"

# Build settings
markdown: kramdown
permalink: /blog/:title/

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
